const SelectStyles = () => ({
	control : (provided) => ({
		...provided,
		border        : "none",
		width         : "100%",
		minHeight     : "26px",
		paddingBottom : "10px",
		paddingTop    : "10px",
		background    : "none",
		borderRadius  : "0px",
		cursor        : "pointer",
		"&:focus"     : {
			border    : "none",
			boxShadow : "none",
		},
		"&:active" : {
			border    : "none",
			boxShadow : "none",
		},
		"&:focus-within" : {
			border    : "none",
			boxShadow : "none",
		},
	}),
	menu : (styles) => ({
		...styles,
		borderRadius  : "0px",
		boxShadow     : "0px 4px 10px rgba(193, 189, 180, 0.2), 0px 0px 1px rgba(193, 189, 180, 0.5)",
		top           : "-55px",
		padding       : "0px !important",
		paddingTop    : "0px !important",
		paddingBottom : "0px !important",
	}),
	menuList : (styles) => ({
		...styles,
		paddingBottom : "0px !important",
		paddingTop    : "0px !important",
	}),
	valueContainer : (styles) => ({
		...styles,
		paddingTop    : "0px !important",
		paddingBottom : "0px !important",
		paddingRight  : "0px !important",
		paddingLeft   : "15px !important",
		marginBottom  : "0px !important",
	}),
	multiValue : (styles) => ({
		...styles,
		backgroundColor : "#f1f3f5",
		color           : "#595f66",
		marginBottom    : "5px",
		borderRadius   	: "8px",
		fontWeight      : 500,
		justifyContent  : "space-between",
		width           : "100% !important",
	}),
	singleValue : (styles) => ({
		...styles,
		fontWeight    : 400,
		lineHeight    : "16px",
		fontFamily    : "Helvetica",
		color         : "#000000",
		textTransform : "uppercase",
		fontSize      : "14px",
	}),
	option : (styles) => ({
		...styles,
		textTransform   : "uppercase",
		fontFamily      : "Helvetica",
		backgroundColor : "#fff",
		color           : "#000",
		fontSize        : "14px",
		fontWeight      : 300,
		padding         : "0px",
		paddingLeft     : "10px !important",
		paddingTop      : "5px !important",
		paddingBottom   : "5px !important",
		width           : "100%",
		cursor          : "pointer",
		transition      : "all ease 200ms",
		margin          : "0px",
		"&:hover"       : {
			backgroundColor : "#E9E4D9",
			color           : "#000",
			transition      : "all ease 200ms",
		},
	}),
	indicatorSeparator : () => ({ display : "none"}),
	// indicatorsContainer : (styles) => ({
	// 	...styles,
	// 	display : "none !important",
	// }),
	dropdownIndicator  : (styles) => ({
		...styles,
		fontWeight : 100,
		"&:hover"  : {
			color : "#000000",
		},
	}),
	placeholder : (styles) => ({
		...styles,
		fontWeight    : 400,
		lineHeight    : "16px",
		fontFamily    : "Helvetica",
		color         : "#000000",
		textTransform : "uppercase",
		fontSize      : "14px",
	}),
	menuPortal : styles => ({ ...styles, zIndex : 9999}),
});

export default SelectStyles;
