const SelectStyles = ({type, leftIcon, dropTopMenu}) => ({
	control : (provided) => ({
		...provided,
		border        : (type === "filled") ? "1px solid black !important" : "none",
		width         : "100%",
		minHeight     : "24px",
		paddingBottom : ((type === "light") || (type === "filled")) ? "0px" : "10px",
		paddingTop    : ((type === "light") || (type === "filled")) ? "0px" : "10px",
		background    : ((type === "light") || (type === "filled")) ? "whithe" : "none",
		borderRadius  : "0px",
		cursor        : "pointer",
		"&:focus"     : {
			border    : "none",
			boxShadow : "none",
		},
		"&:hover" : {
			border    : "none",
			boxShadow : "none",
		},
		"&:active" : {
			border    : "none",
			boxShadow : "none",
		},
		"&:focus-within" : {
			boxShadow : "none",
			border    : "none",
		},
	}),
	menu : (styles) => ({
		...styles,
		borderRadius  : "0px",
		fontFamily    : "Helvetica",
		fontSize      : "12px",
		fontWeight    : 300,
		boxShadow     : "0px 4px 10px rgba(193, 189, 180, 0.2), 0px 0px 1px rgba(193, 189, 180, 0.5)",
		top           : !dropTopMenu && "-6px",
		padding       : "0px !important",
		paddingTop    : "0px !important",
		paddingBottom : "0px !important",
	}),
	menuList : (styles) => ({
		...styles,
		paddingBottom : "0px !important",
		paddingTop    : "0px !important",
	}),
	valueContainer : (styles) => ({
		...styles,
		paddingTop    : "0px !important",
		paddingBottom : "0px !important",
		paddingRight  : "0px !important",
		paddingLeft   : ((type !== "light") || !leftIcon) ? "6px !important" : "27px",
		marginBottom  : "0px !important",
	}),
	multiValue : (styles) => ({
		...styles,
		backgroundColor : "#f1f3f5",
		color           : "#595f66",
		marginBottom    : "5px",
		borderRadius   	: "8px",
		fontWeight      : 500,
		justifyContent  : "space-between",
		width           : "100% !important",
	}),
	singleValue : (styles) => ({
		...styles,
		fontWeight    : 300,
		lineHeight    : "12px",
		color         : "#000000",
		letterSpacing : "0.05em",
		textTransform : type !== "light" && "uppercase",
		fontSize      : "12px",
	}),
	option : (styles) => ({
		...styles,
		textTransform   : type !== "light" && "uppercase",
		fontFamily      : "Helvetica",
		backgroundColor : "#fff",
		color           : "#000",
		fontSize        : "12px",
		fontWeight      : 300,
		letterSpacing   : "0.05em",
		lineHeight      : "12px",
		padding         : "0px",
		paddingLeft     : "10px !important",
		paddingBottom   : "5px !important",
		paddingTop      : "5px !important",
		width           : "100%",
		cursor          : "pointer",
		transition      : "all ease 200ms",
		margin          : "0px",
		"&:hover"       : {
			backgroundColor : "#E9E4D9",
			color           : "#000",
			transition      : "all ease 100ms",
		},
	}),
	indicatorSeparator : () => ({ display : "none"}),
	dropdownIndicator  : (styles) => ({
		...styles,
		fontWeight : 100,
		color      : "#000",
	}),
	placeholder : (styles) => ({
		...styles,
		fontWeight    : 300,
		lineHeight    : "12px",
		fontSize      : "12px",
		letterSpacing : "0.05em",
		textTransform : type !== "light" && "uppercase",
		color         : ((type === "light") || (type === "filled")) ? "#000000" : "#000000",
	}),
	menuPortal : styles => ({ ...styles, zIndex : 3}),
});

export default SelectStyles;
