yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules
npmScopes:
  pqina:
    npmRegistryServer: "https://npm.pqina.nl/"
    npmAlwaysAuth: true
    npmAuthToken: l1k0NC33tHJwDvdbYTP7x.IFRiwSVWGSzmBJrPst4SSjqtyERLxNe